export const CourseActions = {
  CREATE_COURSE: 'CREATE_COURSE',
  LOAD_COURSES: 'LOAD_COURSES',
  UPDATE_COURSE: 'UPDATE_COURSE',
  REMOVE_COURSE: 'REMOVE_COURSE'
};

export const AuthorActions = {
  CREATE_AUTHOR: 'CREATE_AUTHOR',
  LOAD_AUTHORS: 'LOAD_AUTHORS',
  UPDATE_AUTHOR: 'UPDATE_AUTHOR',
  REMOVE_AUTHOR: 'REMOVE_AUTHOR'
};
